### ISSUE TITLE
how to deal with kwargs 

### ISSUE THREAD

**Issue by koaning** [koaning/evol#1]
```
def init_func():
    return 1


def eval_func(x):

    return x


def pick_two_random_parents(population):
    return random.choices(population, k=2)


def pick_n_random_parents(population, n_parents=2):
    return random.choices(population, k=n_parents)


def combine_two_parents(mom, dad):
    return (mom+dad)/2


def general_combiner(*parents):
    return sum(parents)/len(parents)

pop1 = Population(init_function=init_func, eval_function=eval_func, size=200)
pop1.survive(n=50).breed(parent_picker=pick_two_random_parents, combiner=combine_two_parents)

pop2 = Population(init_function=init_func, eval_function=eval_func, size=200)
pop2.survive(n=50).breed(parent_picker=pick_n_random_parents, combiner=general_combiner)
```

What is a nice way to change the `n_parents` parameter? Something like;

```
pop2.survive(n=50).breed(parent_picker=pick_n_random_parents, combiner=general_combiner, n_parents=3)
```

**Comment by koaning** [comment]
@rogiervandergeer any opinion on this?

**Comment by rogiervandergeer** [comment]
I see several options

### 1. Accept `kwargs` and pass them to both functions

We could have `.breed()` accept `kwargs` and pass these to both the `parent_picker` as well as the 
the `combiner`. This would require both functions the same parameters (or `kwargs`), which is
rather ugly.

### 2. Accept `kwargs` and pass them to the functions which accept them

Just like _1._, have `.breed()` accept `kwargs` and pass these to the `parent_picker` and the `combiner`
only if these functions have a parameter with the same name (we can look that up using `getargspec(fct).args`). That would remove the requirement for the functions to accept
the same parameters. The situation does get rather complex - I won't be too easy to pick up what is
going on when passing arguments. 

### 3. Only allow `n_parents` as parameter

Any other parameters are not allowed, and `n_parents` is only passed to `parent_picker` when provided by the user.

### 4. Provide decorators for provided functions

We wouldn't have to pass additional arguments. The syntax would be something like 
```
pop.survive(n=50).breed(parent_picker=pick_random(n=2), combiner=general_combiner)
```

**Comment by koaning** [comment]
### Option 1

Requiring every function to have such `**kwargs` is indeed ugly. 

### Option 2

This complexity feels very error prone. 

### Option 3

This feels rather limiting and it really does feel like this `n_parents` thing is a special case of something we ought to have. 

### Option 4

We will never be able to prevent this pattern. I doubt that this is what we want to supply as best practice in any example though. 

### Option 5 

I think I solved this problem in a previous iteration of `evol` by wrapping it internally. 

```
def breed(self, parentpicker: Callable, create_chromosome: Callable, n_max: int=None, **kwargs) -> 'Evolution':
    def _breed(population, n_max=n_max):
        if not n_max:
            n_max = population.size
        for new_individual in range(len(population), n_max):
            parents = parentpicker(population, **kwargs)
            child_chromosome = create_chromosome(*parents, **kwargs)
            child = Individual(chromosome=child_chromosome, eval_func=population.eval_func)
            population.individuals.append(child)
        return population
    self.chain.append(_breed)
    return self
```

I did this consistently for all verbs but this was in the time that I had a `self.chain` list of verbs I wanted to apply. Note that `.breed()` is *not* run and instead `._breed()` is run. Technically we could do a similar thing and it removes the downside of option 1 and is still not as ugly as option 2. 

@rogiervandergeer : does this feel like a balance to you or a compromise?

**Comment by rogiervandergeer** [comment]
@koaning, I think we're mixing things up here. The solution you propose deals with the functions stored in the `chain` of an Evolution. We also need to solve this in the `Population`, such that you can do `pop.breed(...)`.

**Comment by koaning** [comment]
Like so? 

```
def breed(self, parentpicker: Callable, create_chromosome: Callable, n_max: int=None, **kwargs) -> 'Evolution':
    def _breed(population, n_max=n_max):
        if not n_max:
            n_max = population.size
        for new_individual in range(len(population), n_max):
            parents = parentpicker(population, **kwargs)
            child_chromosome = create_chromosome(*parents, **kwargs)
            child = Individual(chromosome=child_chromosome, eval_func=population.eval_func)
            population.individuals.append(child)
        return population
    return _breed(self)
```

**Comment by koaning** [comment]
I'll just be copying part of the slack chat here.

```
def make_function_accept_all_args(func):
    def result(arg, **kwargs):
        try:
            func(arg, **kwargs)
        except TypeError:
           func(arg, **{k: v for k, v in kwargs.items() if k in getargspec(fct).args})
    return result
```

**Comment by rogiervandergeer** [comment]
See #6
