### ISSUE TITLE
how to do a grid search

### ISSUE THREAD

**Issue by koaning** [koaning/evol#3]
Depending on the problem you're dealing with, you may want to supply the population with a predefined list of chromosomes instead of a function to generate a mere individual. This way the end user might specify a grid to start from. 

 We could accomodate for this flow by adding a `init_chromosomes` parameter to `Population.__init__` where we would check that either `init_func` or `init_chromosomes` are used. 

Any thoughts for/against this? After thinking it over it seems like the only way to do this in our current API is to first generate a population and next overwrite all the individuals.

**Comment by rogiervandergeer** [comment]
I agree; you may also want to be able to supply the population with a set of chromosomes obtained elsewhere or stored in a pickle. 

You might argue that by default a `Population` is initialised with a predefined set of chromosomes, and that generating them using the `init_func` is a special case. In that case we can let the `__init__` accept only `init_chromosomes` (we could even name that `chromosomes`), and make a 

```
@classmethod
def generate(cls, init_func, eval_func, size=100):
    chromosomes = [init_func() for _ in range(size)]
    return cls(chromosomes=chromosomes, eval_func=eval_func)
```

to allow generating a population with an init function.

**Comment by koaning** [comment]
It feels hard to imagine what is the preferable method `init_func` vs `init_chromosomes`. Using a classmethod feels like an advanced bother for somebody who is using the library for the first time.

**Comment by rogiervandergeer** [comment]
I guess it would be much easier to start with something like

```
chromosomes = [init_func() for _ in range(100)]

population = Population(chromosomes)
```

than
```
population = Population(init_func, n=100)
```

So I guess we should prefer to use the former in tutorials. 

The alternative, `population = Population.generate(init_func, n=100)` shouldn't be too unfamiliar for anyone who ever used pandas (e.g. `pd.DataFrame.from_dict`).

**Comment by koaning** [comment]
That is convincing enough for me. Will add this feature to branch that I'm working on in the bus.

**Comment by koaning** [comment]
https://github.com/koaning/evol/pull/2 should adres this.

**Comment by koaning** [comment]
merged and done.
