### ISSUE TITLE
The case for a chromosome class

### ISSUE THREAD

**Issue by rogiervandergeer** [koaning/evol#5]
It's great that we can accept literally _any_ object as a chromosome, in combination with two functions that mutate and combine the chromosomes (and one that evaluates them, of course). For beginners,
simple cases and the tutorials that is the way to go. 

For more complex cases (e.g. chromosomes that have two sets of genes and a sex) one is likely
going to implement a class that handles the initialisation, mutation and combination of these 
chromosomes. Such a class can always have the same basic interface: it is instantiated using `Chromosome()`, it is mutated by `chromosome.mutate()` and it can be combined with a number
of other chromosomes by `chromosome.combine(*chromosomes)`. Depending on the problem,
one might be able to evaluate it using `chromosome.evaluate()`. 

Forgetting about the evaluation for now*, we of course allow for the usage of such a class; `Population.generate(init_func=Chromosome)` will take care of initialisation, `pop.mutate(lambda c: c.mutate())` will take care of mutation and `lambda chromosomes: chromosomes[0].combine(*chromosomes[1:])` handles combination.

But, I don't like the fact that we need the lambda functions. Shouldn't we allow the user to specify
no mutation and combination functions, and in such a case look for the methods of the class?

.* Evaluation is a little tricky, since for competitive problems one may need other chromosomes to
evaluate properly. Hence we cannot put this in a fixed form.

**Comment by koaning** [comment]
Nothing stops a user to implement their own chromosome object. In fact, part of the power of the current approach is that we really do not care what voodoo object people want to play with. 

My problem with this approach is that in practice, you'll most likely want to try out many different mutation functions and different breed tactics. How would you have multiple mutate methods in a chromosome class?

**Comment by rogiervandergeer** [comment]
Good point. Of course one could pass arguments, but that would get out of hand pretty quickly. That
means that whenever one wants to try multiple combining / mutating tactics with a single population one would need to
provide a function -- irrespective of whether one uses a `Chromosome` class or not.

I myself would opt for defining multiple populations, each with a different class of chromosome with
its own methods. But I certainly do not want to impose that on anyone else.

I'll think about alternatives to get rid of these ugly lambda functions

**Comment by koaning** [comment]
The power is that currently nothing is stopping you from making a class with a classmethod. 

This discussion feels a bit like the general object oriented vs. functional programming debate.

**Comment by koaning** [comment]
Close the issue in the meantime?
