### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by rogiervandergeer** [koaning/evol#8]
Currently we only support python 3.6, since we use f'{string}' syntax. On many platforms python3.6 isn't readily available (e.g. raspberry pi, on which I haven't even been able to compile it so far) - don't we want to support 3.4 too?

**Comment by koaning** [comment]
Would you *ever* want to run this on such a system? 

Dynamic typing may also require newer system.

**Comment by rogiervandergeer** [comment]
Do not underestimate the number of people toying around with these systems. Also, for example Ubuntu 16.04 does not provide a means to easily install 3.6.

**Comment by koaning** [comment]
Are we willing to lose dynamic typing in order to support python2.x?

**Comment by rogiervandergeer** [comment]
No! Python 2 is history in my opinion. All these older systems do provide 3.4 or 3.5.

**Comment by rogiervandergeer** [comment]
I'll make a branch and see how much I have to change to be able to run in 3.4. Then we can decide.

**Comment by koaning** [comment]
I am curious to hear about systems where it is easy to install python 3.4 but not 3.6. I am fine with more support if we only loose the `f"{}"` notation.

**Comment by rogiervandergeer** [comment]
Ubuntu 16.04 doesn't have a python3.6 package available
